### ISSUE TITLE
rock64: model and compatible string not correct

### ISSUE THREAD

**Issue by apritzel** [rock64-linux/kernel#2]
Hi,
thanks for doing the rename of the .dts file, this now looks right!
But the model name and compatible string are still not correct.
"model" specifies the name of the *device*, which means the board in our case. So the vendor here is Pine64, not Rockchip (which is the SoC vendor and correctly used in the compatible fallback).
So I think those lines should read:
    model = "Pine64 Rock64";         (or just Rock64, depends on what TL Lim prefers)
    compatible = "pine64,rock64", "rockchip,rk3328";

The SoC prefix is really only used in the filename. Compare the Pine64 DT for an example.

Cheers,
Andre.

**Comment by wlcheah** [comment]
Hi Andre,

Thanks for the feedback! Updated kernel and u-boot .dts files accordingly.
